### ISSUE TITLE
UTF-8 versus ISO-8859-1

### ISSUE THREAD

**Issue by amaliesander** [m4um4u1/SDUprojectgrp26#31]
2 har problemer med ÆØÅ - kræves at parseren ændres til ISO-8859-1 (giver problemer for resten)

**Comment by Jessen13** [comment]
Måske kan problemet "løses" ved at kaste en exception hvis æøå fra Scanner ikke passer der siger at den computer de har ikke er kompatibel med programmet.
Så viser vi at vi er klar over der et problem

**Comment by Jessen13** [comment]
Forsøg med detektion af file encoding fejlede

String s = System.getProperty("file.encoding");
reader = new Scanner(System.in, s);
