### ISSUE TITLE
Command DEPOSIT

### ISSUE THREAD

**Issue by Jessen13** [m4um4u1/SDUprojectgrp26#45]
Hvis man skriver "smid ud" så kan man stadige smide en ting ud fra ens inventory. Det virker ligegyldigt hvad man skriver efter smid. Det siger også ud til den smider alle ting ud fra ens inventory.
Dette er med det nyeste program.

**Comment by m4um4u1** [comment]
har skiftet til den version hvor den bare printer forkert
